apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grilli-ingress
  namespace: grilli
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: grilli.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grilli-service
                port:
                  number: 80
