apiVersion: v1
kind: Service
metadata:
  name: grilli-service
  namespace: grilli
spec:
  type: NodePort
  selector:
    app: grilli
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036
